TempDriver: Temperature.class TempDriver.class

Temperature.class: Temperature.java
	javac -deprecation Temperature.java

TempDriver.class: TempDriver.java
	javac -deprecation TempDriver.java

clean:
	rm -f *.class *~ *# *.o

